version: "3.8"

services:
  keyword-hasher-job:
    container_name: "keyword-hasher-job"
    build:
      context: "./src"
      dockerfile: "./KeywordHasherJob/Dockerfile"
    volumes:
    - "${JoobleListSourcePath}:/JoobleList"
    env_file:
      - ".env"
    environment:
      JoobleListPath: "/JoobleList"
    restart: "no"
